name: Airtable Master List Generation

on:
  push:
    branches:
      - master

jobs:
  airtable-generation:
    name: Airtable Master List Generation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Airtable generation
        run: |
          yarn generate:master-list -v -o airtable
          echo "Airtable Master List generated successfully."
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
