name: Generate READMEs

on:
  push:
    branches:
      - changeset-release/develop
env:
  NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
jobs:
  generate-readmes:
    name: Generate READMEs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - name: Generate Documentation
        run: |
          yarn generate:master-list -v
          yarn generate:readme -a -v
          git add .
          yarn lint-staged
          git commit --amend --no-edit
          git push --force
          echo "README(s) generated successfully."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
